# Generated by Django 6.0 on 2025-12-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_company_status_companygroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='original_email',
            field=models.EmailField(blank=True, help_text='Stores original email when user is soft-deleted', max_length=254, null=True),
        ),
    ]
