# Generated by Django 5.2.7 on 2025-12-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_company_id_alter_subscriptionplan_id_and_more'),
        ('account', '0003_alter_company_status'),
        ('account', '0004_user_is_disabled_user_original_email'),
    ]

    operations = [
    ]
