# Generated by Django 4.2.25 on 2025-12-21 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_company_id_alter_subscriptionplan_id_and_more"),
        ("account", "0003_alter_company_status"),
        ("account", "0005_alter_company_id_alter_companygroup_id_and_more"),
    ]

    operations = []
