# Generated by Django 4.2.25 on 2025-12-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_merge_20251221_0652"),
        ("account", "0005_merge_20251221_0916"),
        ("account", "0006_merge_20251221_0637"),
    ]

    operations = []
