# Generated by Django 6.0 on 2025-12-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_company_id_alter_subscriptionplan_id_and_more'),
        ('account', '0007_merge_20251222_0844'),
    ]

    operations = [
    ]
