# Generated by Django 6.0 on 2025-12-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_merge_20251223_0745'),
        ('account', '0009_alter_companygroup_id_alter_employeeprofile_id'),
    ]

    operations = [
    ]
