# Generated by Django 6.0 on 2025-12-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_companycourseassignment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='icon',
            field=models.CharField(blank=True, default='book', help_text="Font Awesome icon name (e.g., 'shield-alt', 'user-secret', 'lock')", max_length=50, null=True),
        ),
    ]
