# Generated by Django 6.0 on 2025-12-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_coursecategory_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategory',
            name='color',
        ),
        migrations.RemoveField(
            model_name='coursecategory',
            name='icon',
        ),
    ]
