# Generated by Django 4.2.25 on 2025-12-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("subject", models.CharField(blank=True, max_length=200)),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="phishing_templates/"
                    ),
                ),
                ("html_content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(model_name="phishingcampaign", name="created_at",),
        migrations.AlterField(
            model_name="phishingcampaign",
            name="sender",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="phishingcampaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="phishingcampaign",
            name="title",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="phishingcampaign",
            name="user_group",
            field=models.CharField(max_length=100),
        ),
    ]
