# Generated by Django 4.2.25 on 2025-12-21 23:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_emailtemplate_remove_phishingcampaign_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phishingcampaign",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="phishingcampaign",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="campaigns.emailtemplate",
            ),
        ),
    ]
