# Generated by Django 4.2.25 on 2025-12-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0003_alter_campaignrecipient_id_alter_emailtemplate_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="phishingcampaign",
            name="ends_at",
            field=models.DateTimeField(
                blank=True, help_text="Phishing campaign expiry date & time", null=True
            ),
        ),
    ]
