# Generated by Django 4.2.25 on 2025-12-22 19:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_campaignrecipient"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="campaignrecipient", unique_together={("campaign", "email")},
        ),
        migrations.CreateModel(
            name="PhishingEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("click", "Click"),
                            ("fall", "Fall"),
                        ],
                        max_length=10,
                    ),
                ),
                ("target_url", models.URLField(blank=True, max_length=1000)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="campaigns.phishingcampaign",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="campaigns.campaignrecipient",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["campaign", "event_type", "created_at"],
                        name="campaigns_p_campaig_a6be6a_idx",
                    ),
                    models.Index(
                        fields=["recipient", "created_at"],
                        name="campaigns_p_recipie_838858_idx",
                    ),
                ],
            },
        ),
    ]
